# CMake generated Testfile for 
# Source directory: /home/yuhan/new/SUF
# Build directory: /home/yuhan/new/SUF/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_cuda_pack_effbits "/home/yuhan/new/SUF/build_debug/test_cuda_pack_effbits")
set_tests_properties(test_cuda_pack_effbits PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;330;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_softmax_gpu_smoke "/home/yuhan/new/SUF/build_debug/test_softmax_gpu_smoke")
set_tests_properties(test_softmax_gpu_smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;343;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(bench_gemm_overlap "/home/yuhan/new/SUF/build_debug/bench_gemm_overlap")
set_tests_properties(bench_gemm_overlap PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;354;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_trunc_task "/home/yuhan/new/SUF/build_debug/test_trunc_task")
set_tests_properties(test_trunc_task PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;367;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_layernorm_task "/home/yuhan/new/SUF/build_debug/test_layernorm_task")
set_tests_properties(test_layernorm_task PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;368;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_staged_softmax "/home/yuhan/new/SUF/build_debug/test_staged_softmax")
set_tests_properties(test_staged_softmax PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;369;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_planner "/home/yuhan/new/SUF/build_debug/test_pfss_planner")
set_tests_properties(test_pfss_planner PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;370;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_async "/home/yuhan/new/SUF/build_debug/test_pfss_async")
set_tests_properties(test_pfss_async PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;371;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_async_stress "/home/yuhan/new/SUF/build_debug/test_pfss_async_stress")
set_tests_properties(test_pfss_async_stress PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;372;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_transformer_async "/home/yuhan/new/SUF/build_debug/test_transformer_async")
set_tests_properties(test_transformer_async PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;373;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_planner_causal "/home/yuhan/new/SUF/build_debug/test_planner_causal")
set_tests_properties(test_planner_causal PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;374;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_gapars_selector "/home/yuhan/new/SUF/build_debug/test_gapars_selector")
set_tests_properties(test_gapars_selector PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;375;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_gpu "/home/yuhan/new/SUF/build_debug/test_pfss_gpu")
set_tests_properties(test_pfss_gpu PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;377;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_trunc_gapars "/home/yuhan/new/SUF/build_debug/test_cuda_trunc_gapars")
set_tests_properties(test_cuda_trunc_gapars PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;378;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_prg "/home/yuhan/new/SUF/build_debug/test_cuda_prg")
set_tests_properties(test_cuda_prg PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;379;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_pred_mask "/home/yuhan/new/SUF/build_debug/test_cuda_pred_mask")
set_tests_properties(test_cuda_pred_mask PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;380;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_packed_pfss "/home/yuhan/new/SUF/build_debug/test_cuda_packed_pfss")
set_tests_properties(test_cuda_packed_pfss PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;381;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_matmul_and_attention_executor "/home/yuhan/new/SUF/build_debug/test_matmul_and_attention")
set_tests_properties(test_matmul_and_attention_executor PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;385;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_matmul_executor "/home/yuhan/new/SUF/build_debug/test_matmul")
set_tests_properties(test_matmul_executor PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;386;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
