# CMake generated Testfile for 
# Source directory: /home/yuhan/new/SUF
# Build directory: /home/yuhan/new/SUF/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_planner_causal_bytes "/home/yuhan/new/SUF/build_release/test_planner_causal_bytes")
set_tests_properties(test_planner_causal_bytes PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;316;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_planner_ragged_bytes "/home/yuhan/new/SUF/build_release/test_planner_ragged_bytes")
set_tests_properties(test_planner_ragged_bytes PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;321;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_planner_effbits_budget "/home/yuhan/new/SUF/build_release/test_planner_effbits_budget")
set_tests_properties(test_planner_effbits_budget PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;326;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_pack_effbits "/home/yuhan/new/SUF/build_release/test_cuda_pack_effbits")
set_tests_properties(test_cuda_pack_effbits PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;344;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_softmax_gpu_smoke "/home/yuhan/new/SUF/build_release/test_softmax_gpu_smoke")
set_tests_properties(test_softmax_gpu_smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;373;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(bench_gemm_overlap "/home/yuhan/new/SUF/build_release/bench_gemm_overlap")
set_tests_properties(bench_gemm_overlap PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;384;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_trunc_task "/home/yuhan/new/SUF/build_release/test_trunc_task")
set_tests_properties(test_trunc_task PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;409;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_layernorm_task "/home/yuhan/new/SUF/build_release/test_layernorm_task")
set_tests_properties(test_layernorm_task PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;410;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_staged_softmax "/home/yuhan/new/SUF/build_release/test_staged_softmax")
set_tests_properties(test_staged_softmax PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;411;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_planner "/home/yuhan/new/SUF/build_release/test_pfss_planner")
set_tests_properties(test_pfss_planner PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;412;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_async "/home/yuhan/new/SUF/build_release/test_pfss_async")
set_tests_properties(test_pfss_async PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;413;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_async_stress "/home/yuhan/new/SUF/build_release/test_pfss_async_stress")
set_tests_properties(test_pfss_async_stress PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;414;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_transformer_async "/home/yuhan/new/SUF/build_release/test_transformer_async")
set_tests_properties(test_transformer_async PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;415;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_planner_causal "/home/yuhan/new/SUF/build_release/test_planner_causal")
set_tests_properties(test_planner_causal PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;416;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_gapars_selector "/home/yuhan/new/SUF/build_release/test_gapars_selector")
set_tests_properties(test_gapars_selector PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;417;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_pfss_gpu "/home/yuhan/new/SUF/build_release/test_pfss_gpu")
set_tests_properties(test_pfss_gpu PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;419;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_trunc_gapars "/home/yuhan/new/SUF/build_release/test_cuda_trunc_gapars")
set_tests_properties(test_cuda_trunc_gapars PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;420;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_prg "/home/yuhan/new/SUF/build_release/test_cuda_prg")
set_tests_properties(test_cuda_prg PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;421;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_pred_mask "/home/yuhan/new/SUF/build_release/test_cuda_pred_mask")
set_tests_properties(test_cuda_pred_mask PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;422;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_packed_pfss "/home/yuhan/new/SUF/build_release/test_cuda_packed_pfss")
set_tests_properties(test_cuda_packed_pfss PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;423;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_beaver_mul "/home/yuhan/new/SUF/build_release/test_cuda_beaver_mul")
set_tests_properties(test_cuda_beaver_mul PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;424;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_trunc_postproc "/home/yuhan/new/SUF/build_release/test_cuda_trunc_postproc")
set_tests_properties(test_cuda_trunc_postproc PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;425;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_horner_cubic "/home/yuhan/new/SUF/build_release/test_cuda_horner_cubic")
set_tests_properties(test_cuda_horner_cubic PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;426;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_cuda_recip_task "/home/yuhan/new/SUF/build_release/test_cuda_recip_task")
set_tests_properties(test_cuda_recip_task PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;427;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_matmul_and_attention_executor "/home/yuhan/new/SUF/build_release/test_matmul_and_attention")
set_tests_properties(test_matmul_and_attention_executor PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;431;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
add_test(test_matmul_executor "/home/yuhan/new/SUF/build_release/test_matmul")
set_tests_properties(test_matmul_executor PROPERTIES  _BACKTRACE_TRIPLES "/home/yuhan/new/SUF/CMakeLists.txt;432;add_test;/home/yuhan/new/SUF/CMakeLists.txt;0;")
